# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c676b30abfed921934a1364249b5da88a011a8bc9ce006fdb5d507839746a14cf80c8ecc585784d18b3d1abb8e86028eec878d6b06d00071497653065d05160

test:
  secret_key_base: 6ddc57667ec448fb6886bf3d1ca68204d99abb86beb41808c369fbf6dd1b6b444ac9e4ca5e841a9c8771027fe2fe97d1f9101c42aab8004c0d6d3eecd8e72442

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
